// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrition_App.Services;

#nullable disable

namespace Nutrition_App.Services.Migrations.DietLogDb
{
    [DbContext(typeof(DietLogDbContext))]
    [Migration("20251120175157_dietlog-migration")]
    partial class dietlogmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Nutrition_App.Entities.DietLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEaten")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightEaten")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DietLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
