// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nutrition_App.Data;

#nullable disable

namespace Nutrition_App.Services.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20251106193029_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Nutrition_App.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FdcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WweiaFoodCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WweiaFoodCategoryId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Nutrition_App.Entities.FoodAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodAttributeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodAttributeTypeId");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodAttributes");
                });

            modelBuilder.Entity("Nutrition_App.Entities.FoodAttributeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodAttributeTypes");
                });

            modelBuilder.Entity("Nutrition_App.Entities.FoodNutrient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int?>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NutrientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("NutrientId");

                    b.ToTable("FoodNutrients");
                });

            modelBuilder.Entity("Nutrition_App.Entities.FoodPortion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GramWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("MeasureUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MeasureUnitId");

                    b.ToTable("FoodPortions");
                });

            modelBuilder.Entity("Nutrition_App.Entities.InputFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngredientDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("IngredientWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("PortionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("InputFoods");
                });

            modelBuilder.Entity("Nutrition_App.Entities.MeasureUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeasureUnits");
                });

            modelBuilder.Entity("Nutrition_App.Entities.Nutrient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");
                });

            modelBuilder.Entity("Nutrition_App.Entities.WweiaFoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WweiaFoodCategoryCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WweiaFoodCategoryDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WweiaFoodCategories");
                });

            modelBuilder.Entity("Nutrition_App.Entities.Food", b =>
                {
                    b.HasOne("Nutrition_App.Entities.WweiaFoodCategory", "WweiaFoodCategory")
                        .WithMany()
                        .HasForeignKey("WweiaFoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WweiaFoodCategory");
                });

            modelBuilder.Entity("Nutrition_App.Entities.FoodAttribute", b =>
                {
                    b.HasOne("Nutrition_App.Entities.FoodAttributeType", "FoodAttributeType")
                        .WithMany()
                        .HasForeignKey("FoodAttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nutrition_App.Entities.Food", null)
                        .WithMany("FoodAttributes")
                        .HasForeignKey("FoodId");

                    b.Navigation("FoodAttributeType");
                });

            modelBuilder.Entity("Nutrition_App.Entities.FoodNutrient", b =>
                {
                    b.HasOne("Nutrition_App.Entities.Food", null)
                        .WithMany("FoodNutrients")
                        .HasForeignKey("FoodId");

                    b.HasOne("Nutrition_App.Entities.Nutrient", "Nutrient")
                        .WithMany()
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("Nutrition_App.Entities.FoodPortion", b =>
                {
                    b.HasOne("Nutrition_App.Entities.Food", null)
                        .WithMany("FoodPortions")
                        .HasForeignKey("FoodId");

                    b.HasOne("Nutrition_App.Entities.MeasureUnit", "MeasureUnit")
                        .WithMany()
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasureUnit");
                });

            modelBuilder.Entity("Nutrition_App.Entities.InputFood", b =>
                {
                    b.HasOne("Nutrition_App.Entities.Food", null)
                        .WithMany("InputFoods")
                        .HasForeignKey("FoodId");
                });

            modelBuilder.Entity("Nutrition_App.Entities.Food", b =>
                {
                    b.Navigation("FoodAttributes");

                    b.Navigation("FoodNutrients");

                    b.Navigation("FoodPortions");

                    b.Navigation("InputFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
